### ISSUE TITLE
"Toggle Profiler" voice command doesn't hide profiler

### ISSUE THREAD

**Issue by jcellswo** [provencher/MRTK-Online#1]
The voice command works when running the program in the unity editor, but not when it is published to the device. This is my experience, at least. The voice commands are enabled and my Quest 2 is unmuted.

**Comment by provencher** [comment]
Voice commands don't work on Oculus platforms, sorry.

**Comment by jcellswo** [comment]
Oh ok. Thanks.

**Comment by jcellswo** [comment]
Just out of curiosity: why would there be a "voice commands" option under "device" in the settings menu on the Quest 2 if they won't work? Do you mean these particular voice commands won't work on oculus platforms?

**Comment by provencher** [comment]
Well there's two parts here:

1. Voice commands on Oculus Quest only work in the Shell / Home space. They're not exposed to developers, as far as I know.

2. Getting MRTK to work with voice commands involves wrapping the speech service of the device, to forward actions to MRTK. There's no such code that exists in MRTK right now for Android devices.

The reason it works in Windows / Unity Editor, is because there is a speech service implemented in MRTK for Windows devices, so even though you're using an Oculus headset, it's the same codepath as any other windows device.

Hope that helps.

**Comment by jcellswo** [comment]
I see. Thanks for the timely response and good explanation.
